### ISSUE TITLE
Zest script to disable or click on a prompt dialog box on Chrome

### ISSUE THREAD

**Issue by V1Reddy** [mozilla/zest#161]
Hi,
I was wondering if there's a way in zest script to auto click or close a dialog prompt box. I am testing the zest script in ZAP scripts section using the Chrome browser, but stuck while continuing forward due to a dialog box that prompts for username and pwd. The rest of the script doesn't continue unless I cancel this prompt. I tried to use all the zest client options to send keys, click, submit, but nothing seems to work for that javascript promt box.

Is there an option in the zest scripts that I need to be using for these JS prompt boxes? Or is there an option in Chrome browser that I force the browser to auto cancel those prompts?

Any help would be much appreciated!

Thanks.

**Comment by thc202** [comment]
If I'm understanding correctly this is #75. Could you confirm?

**Comment by V1Reddy** [comment]
Hi @thc202,
Yes, it is same as #75.  

Sorry for opening a duplicate issue!

**Comment by thc202** [comment]
No worries. Merging into that one then.

**Comment by thc202** [comment]
You sure the dialogue shown was from JS and not native? If the latter it would not be #75 :)

**Comment by V1Reddy** [comment]
Yeah, it's a dialogue box from JS.

**Comment by psiinon** [comment]
A simple test page which generates a dialog would be very useful :)
Obviously we can create one, but if you can give us one which matches your case then we'll know when fixed it.

**Comment by thc202** [comment]
@V1Reddy ok, I was asking again because Chrome does not allow to interact with the (native) dialogue that prompts for credentials (e.g. basic/digest HTTP authentication).

@psiinon indeed, that would be helpful.

**Comment by V1Reddy** [comment]
@thc202 ,
Maybe, I am stating it wrong. It's a prompt for username and pwd and it's a custom JS prompt box, don't think it's native. But I will look into it again and confirm.

@psiinon 
Sure thing, I will create a similar one and send it you guys.

Thanks again for your help guys!
