### ISSUE TITLE
Migration to a maintained version of the Apache HTTP Client

### ISSUE THREAD

**Issue by mgmechanics** [mozilla/zest#168]
Zest contains Apache HTTP Client 3.1 which is unmaintained since long time ago. Is there serious interest to update it to Apache HTTP Client 4 or better?

The company I am working for uses Zest internally. It is doing great but our source scan raises security errors of highest level because of the outdated HTTP client. Thus I already updated the HTTP Client to version 4.5.5. If there serious interest I can ask if I can merge my changes into the public code base.

**Comment by thc202** [comment]
I'm +1 to the change, but worth noting that it will break binary compatibility (if we completely drop Commons HttpClient).

**Comment by psiinon** [comment]
+1 as well.
Do we really need binary compatibility? 
Zest script compatibility is the important thing to maintain :)

**Comment by thc202** [comment]
Well, this change will break Zest add-on, but not a problem we can update it easily :)

**Comment by mgmechanics** [comment]
> Zest script compatibility is the important thing to maintain :)
I can run the same Zest scripts than before the change. org.mozilla.zest.core.v1.ZestRequest works with class Cookie from the Apache HTTP Client 4.5.5.

This is possible because JSON from the Class Cookie from HTTP Client 3.1 can be de-serialised in to objects of the class Cookie  in the Apache HTTP Client 4.5.5.

Everything else in the package org.mozilla.zest.core.v1 was not changed.

**Comment by mgmechanics** [comment]
The changes took place in the class org.mozilla.zest.impl.ZestBasicRunner. There are some bigger changes because before migration to HTTP Client 4 I isolated all methods from this class using the HTTP Client 3 in a new class. ZestBasicRunner holds an interface of this class which gets an instance of the new class at runtime. This makes further migrations (Apache HTTP Client 5 is in the beta version) easier.

**Comment by mgmechanics** [comment]
I ask my boss if I can get a budget for this.

**Comment by thc202** [comment]
Which version/commit are you basing your work on? Asking because #118 refactored `ZestBasicRunner` to allow that.

**Comment by mgmechanics** [comment]
I did the migration on the master branch. I have checked [#118](https://github.com/mozilla/zest/pull/118). That looks good. You have already done an important part of the work.

A) ZestCookie: Good idea. Makes Zest independent from particular HTTP clients.

B) org.mozilla.zest.impl.CommonsHttpClient implements ZestHttpClient: Almost the same as my approach. I think I can begin. Have to ask for procedure/budget first.

**Comment by thc202** [comment]
Note that the work should be done in the `develop` branch (`master` is being used only for tagging releases).

Cool, let us know how that goes.

**Comment by mgmechanics** [comment]
Of course, in the develop branch.

**Comment by mgmechanics** [comment]
I did the work and made the pull request [#171](https://github.com/mozilla/zest/pull/171)

**Comment by mgmechanics** [comment]
Tests were done successfully by running examples/BodgeIt_Register_XSS.zst against a dummy service so I could check the requests made by the zest runner.

**Comment by mgmechanics** [comment]
Do you plan to include the new HTTP client for the next release?

**Comment by thc202** [comment]
Sure, good to get this change in (added to milestone).
