### ISSUE TITLE
Update Selenium

### ISSUE THREAD

**Issue by mgmechanics** [mozilla/zest#169]
While the Zest Runner works fine with the current version of Selenium included in it, we (at a major German company) have some headaches with it. Our source scan by Nexus IQ yields  "Policy D1 High Security Threat V1" with highest level for the following two dependencies:

org.eclipse.jetty:jetty-util:9.4.1.v2017012
xerces:xercesImpl:2.11.0

org.eclipse.jetty:jetty-util:9.4.1.v20170120 comes via org.seleniumhq.selenium:selenium-server:jar:3.4.0

xerces:xercesImpl:2.11.0 comes via org.seleniumhq.selenium:selenium-server:jar:3.4.0 and/or org.seleniumhq.selenium:selenium-java:jar:3.4.0

I tried to update Selenium to the next version, 3.5.1, but was not successful because this change caused one unit test to fail. Can you please do the update?

**Comment by thc202** [comment]
I thought we were already using a newer version, will look into that.

**Comment by thc202** [comment]
Yeah, it was done in #159 (at least to 3.11.0), we still need to release a new version though.
