### ISSUE TITLE
Add a `ZestClient...` `elementType` to wait a certain time before running the next statement

### ISSUE THREAD

**Issue by Pamplemousse** [mozilla/zest#217]
(More a feature request than a bug)

I did not find any statements allowing to "pause" for a certain time.

Given that certain webpages have timeouts and processing delays, it might be necessary for automated scripts to wait for the page to "react" to previous changes.

**Comment by thc202** [comment]
`ZestActionSleep` should do that.

**Comment by Pamplemousse** [comment]
10 seconds sounds like a lot, especially for "modern" web-applications whose features rely heavily on client interactions...

`ZestActionSleep` seems to be what I was looking for!

**Comment by thc202** [comment]
That's at most (in which case the script will fail).

**Comment by Pamplemousse** [comment]
Sorry, I am not sure I get it:

You said `ZestClientElement` have an implicit wait of 10 seconds...
So, if the element to be clicked is not on the page, the "Zest runner" will wait until it appears (for a maximum of 10 seconds)?

**Comment by thc202** [comment]
Yeah.
